apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-py
spec:
  selector:
    matchLabels:
      app: docker-py
  template:
    metadata:
      labels:
        app: docker-py
    spec:
      containers:
      - name: docker-py
        image: docker-py
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
        securityContext:
          privileged: true
      volumes:
      - name: docker-socket-volume
        hostPath:
          path: /var/run/docker.sock
          type: File